services:
  backend:
    build:
      context: ./backend

    container_name: flowzen-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend

    container_name: flowzen-frontend

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://localhost:5000/api

    depends_on:
      - backend

    restart: unless-stopped